### ISSUE TITLE
Dynamically update the code

### ISSUE THREAD

**Issue by toujames** [ngstack/code-editor#1030]
Is there a way to dynamically update the code once the editor is loaded?

For instance, I want to be able to load code from a file after the editor is loaded.
Just changing the `codeModel.value` property doesn't seem to change on the editor.

Thanks!

**Comment by LiamKenneth** [comment]
Hey @toujames I had the same issue and came looking for answers but I figured it out.

You need to make a new instance of `codeModel` 

`this.codeModel = JSON.parse(JSON.stringify(this.codeModel));`

then you can set the value and it will take effect

**Comment by toujames** [comment]
Wow. thanks @LiamKenneth  that works!
