### ISSUE TITLE
Dependency on unpkg.com breaks package

### ISSUE THREAD

**Issue by dave-c-vt** [ngstack/code-editor#1138]
today, unpkg.com has an outage for the monaco modules

https://github.com/ngstack/code-editor/blob/e36e422d8e465eaf45a373e24ff48e0d73cff8e8/projects/code-editor/src/lib/services/code-editor.service.ts#L26

https://github.com/mjackson/unpkg/issues/358

should switch to using jsdelivr using this base:

https://cdn.jsdelivr.net/npm/monaco-editor/min/

**Comment by dave-c-vt** [comment]
may be fixed by https://github.com/ngstack/code-editor/pull/1139

**Comment by erickaranibar** [comment]
Do you think there is a way to import monaco modules locally?

**Comment by DenysVuika** [comment]
the readme describes the offline setup, @erickaranibar. the CDN was changed to a new location
