### ISSUE TITLE
Code editor not refreshing when updating the width

### ISSUE THREAD

**Issue by ToberoCat** [ngstack/code-editor#1145]
I pu the code editor into an split panel, where the useris able to drag it to make the window bigger. Sadly, the window doesn't refresh automatically.

Is there a way to force it to rerender?

Image with the editor on load:
![grafik](https://user-images.githubusercontent.com/67831042/232154418-3ba42463-ffd0-41c9-839d-31348ce24cb1.png)

Image of the editor when it got dragged around (Stayed at the same size):
![grafik](https://user-images.githubusercontent.com/67831042/232154458-df723302-c65c-4698-888e-9cbe04ef51b3.png)

**Comment by DenysVuika** [comment]
see https://github.com/ngstack/code-editor/issues/995#issuecomment-1733503267
