### ISSUE TITLE
Support Standalone Components - Angular 17

### ISSUE THREAD

**Issue by dharders** [ngstack/code-editor#1268]
New Angular CLI projects and generated Components default to `standalone=true` now. 

NgModules are no longer encouraged so it would be great for `ngstack/code-editor` to become standalone too.  Or at least update your docs on how to get this library/component to work with a blank CLI created app with v17+.

Thanks for the great library wrapper!

**Comment by dharders** [comment]
I should note that I had to change some things to workaround the NgModule stuff and `CUSTOM_ELEMENTS_SCHEMA` just to get my existing app to compile with v17. Although I still don't receive any `loaded()` or `valueChanged($event)` events so the editor is still not working.

Changes I made were:

`app.config.ts`
```typescript
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { CodeEditorModule } from '@ngstack/code-editor';

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), 
    importProvidersFrom(CodeEditorModule.forRoot(
      {
        baseUrl: 'assets/monaco-editor'
      }
    ))
  ]
};
```

`code-editor.component.ts`
```typescript
import { CUSTOM_ELEMENTS_SCHEMA, Component, Input, OnInit } from '@angular/core';
import { CodeModel } from '@ngstack/code-editor';
import { CodeService } from '../services/render/code.service';
import {editor, Range} from 'monaco-editor'

@Component({
  selector: 'app-code-editor',
  standalone: true,
  imports: [],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
	template: `
               <ngs-code-editor class="caddercode"
			[theme]="theme"
			[codeModel]="codeModel"
			[options]="options"
			(loaded)="monacoLoaded()"
			(valueChanged)="onCodeChanged($event)">
		</ngs-code-editor>
  `,
 ...
```


Any clues on where to from here?

**Comment by DenysVuika** [comment]
The `imports` section in your case is empty, it should be pointing to the modules

**Comment by DenysVuika** [comment]
The [6.0.0](https://github.com/ngstack/code-editor/releases/tag/v.6.0.0) supports Angular standalone components in the demo application, and using code editor component from within the standalone components. I will see how to make the code editor itself a standalone closer to the 7.0.0 release and Angular 17 support
