### ISSUE TITLE
Formatting code to json

### ISSUE THREAD

**Issue by othAs-dev** [ngstack/code-editor#1294]
Hello, thank you for your precedent answer on my issue.
However, your answer didn't help me because when I see your JSON format example, I notice that:

value: [
    '{',
    '      "$schema": "http://custom/schema.json",',
    '      "type": "button"',
   '}'
].join('\n'),

but if we remove the initial spaces before `$schema` and `type` like this:

     
value: [
'{',
' "$schema": "http://custom/schema.json",',
' "type": "button"',
'}'
].join('\n'),

the text's format is still good because we can type JSON. However, the code doesn't have a proper format. I want consistent indentation, similar to Prettier in our IDE. 

Can you help me with this problem, please?

**Comment by DenysVuika** [comment]
The editor has right-click actions with formatting options

<img width="1417" alt="Screenshot 2024-02-08 at 2 59 33 PM" src="https://github.com/ngstack/code-editor/assets/503991/fa410f91-140b-4a2f-94f2-3f5556c39d1d">

**Comment by othAs-dev** [comment]
Ok cool, thank you for that but now is it possible to format the json on the data loading for the first time. 

Because I don't want to let the user make a right click and choice formatting data for have a good format 😅 

Thank you very much for your help

**Comment by DenysVuika** [comment]
With latest 7.2.0, it's now possible calling formatting commands for underlying monaco editor, see https://github.com/ngstack/code-editor/tree/v.7.2.0?tab=readme-ov-file#accessing-code-editor-instance and there's demo project update with the toolbar and button that runs formatting on click
