### ISSUE TITLE
Editor not works with standAlone components 

### ISSUE THREAD

**Issue by AdamsContreras999** [ngstack/code-editor#1372]
import assets of monaco error with component standAlone
![image](https://github.com/ngstack/code-editor/assets/90850547/f12e91d9-6c0c-42e1-8d7c-b75ac5931696)

and also return error when call ngs
![image](https://github.com/ngstack/code-editor/assets/90850547/8dc0e9c5-5f61-4308-a01b-8d773253922b)
<ngs-code-editor/>

please can you update documentation or write in this ticket how implement the editor with standAlone Components?

this problem evit works good this editor 

I have
-angular 18.0.1
-    "@ngstack/code-editor": "^7.2.0",
 -   "monaco-editor": "^0.47.0",
 
 
 
 @DenysVuika i hope can you help me

**Comment by DenysVuika** [comment]
You are importing CommonModule, as well as a bunch of Material Modules, what's the concern about Code Editor? can you import it the same way?

**Comment by AdamsContreras999** [comment]
> You are importing CommonModule, as well as a bunch of Material Modules, what's the concern about Code Editor? can you import it the same way?

That's right, I import those necessary modules into the component because it is a standAlone component, and because I need those modules for that component to work, but when I import, but code editor cannot be imported there, I attached the error that returns in the image

@DenysVuika

**Comment by craigiswayne** [comment]
I have the same issue, i.e. importing into a standalone component

So what I did was create a separate module, and imported that module into my standalone component

So it now at least compiles

<img width="457" alt="image" src="https://github.com/user-attachments/assets/a3c7aba7-768f-4d27-9a37-62d77cfd6682">

<img width="455" alt="image" src="https://github.com/user-attachments/assets/9071594b-e6dd-4e6c-a3ab-9470b04002f4">



However at runtime, i now get the following error:

<img width="687" alt="image" src="https://github.com/user-attachments/assets/7111f060-9085-41c6-8bc5-2647a7610a5e">

```
TypeError: Cannot read properties of undefined (reading 'editor')
    at _CodeEditorService.createModel (ngstack-code-editor.mjs:107:24)
    at _CodeEditorComponent.setupEditor (ngstack-code-editor.mjs:533:38)
    at _CodeEditorComponent.<anonymous> (ngstack-code-editor.mjs:522:10)
    at Generator.next (<anonymous>)
    at chunk-R7GQRDZ6.js?v=5ae53e92:49:61
    at new ZoneAwarePromise (zone.js:2702:25)
    at __async (chunk-R7GQRDZ6.js?v=5ae53e92:33:10)
    at _CodeEditorComponent.ngAfterViewInit (ngstack-code-editor.mjs:521:27)
    at callHookInternal (core.mjs:5136:14)
    at callHook (core.mjs:5163:13)
```

and this is the line causing the problem:

<img width="771" alt="image" src="https://github.com/user-attachments/assets/7eedb5a0-edce-4f29-b0cd-c62d0585ca1f">


```
createModel(value, language, uri) {
    return this.monaco.editor.createModel(value, language, this.monaco.Uri.file(uri));
  }
```

I'm gonna keep fiddling to see if i can figure this out

**Comment by craigiswayne** [comment]
after some digging i've found that the event triggered after the code box is loaded, does not return monaco

```javascript
codeEditorService.loaded.subscribe(event => {
      this.setup(event.monaco);
    });
```

So when it tries to setup, it passes through a `null` value, and that causes the other errors


![image](https://github.com/user-attachments/assets/2cef3e9a-8257-48b9-9fc1-0b2f82091e4d)

**Comment by AdamsContreras999** [comment]
> after some digging i've found that the event triggered after the code box is loaded, does not return monaco
> 
> ```js
> codeEditorService.loaded.subscribe(event => {
>       this.setup(event.monaco);
>     });
> ```
> 
> So when it tries to setup, it passes through a `null` value, and that causes the other errors
> 
> ![image](https://private-user-images.githubusercontent.com/5500952/362241567-2cef3e9a-8257-48b9-9fc1-0b2f82091e4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDcyNjgsIm5iZiI6MTcyNDg0Njk2OCwicGF0aCI6Ii81NTAwOTUyLzM2MjI0MTU2Ny0yY2VmM2U5YS04MjU3LTQ4YjktOWZjMS0wYjJmODIwOTFlNGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTIwOTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUzZjY3MTU0M2JhZTE4YzkyMDU3NGI4YmNkMDhjNDdkZWUxZjQ4MjU2ZjI1MDMyN2I5MDRmMzdkYTU3YTFmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.bOpkIdL8vUENdM9FJtRAlk5tNsGfbdZjrzBmDWxoxvs)

please @DenysVuika can you help us?

**Comment by craigiswayne** [comment]
not to distract from this repo, 

however I tried a different package, which is sort of a wrapper for the Monaco editor as well

https://www.npmjs.com/package/ngx-monaco-editor-v2?activeTab=readme

that's worked for me, and yes I'm still using standalone components

Good luck!

**Comment by DenysVuika** [comment]
The component is fully standalone with the 9.0.0 release: https://github.com/ngstack/code-editor/releases/tag/v.9.0.0

Please check the updated readme or the standalone apps (single/multiple editors)
