### ISSUE TITLE
problem with the editor's width

### ISSUE THREAD

**Issue by othAs-dev** [ngstack/code-editor#1373]
Hello, 

I have a problem with the width of the editor i have a blank space on the right. And i didn't know how to fix that.
Help me to fix that please 

Here you have the component : 
<img width="1437" alt="Capture d’écran 2024-07-19 à 15 20 18" src="https://github.com/user-attachments/assets/c18f09b3-a99b-43da-930a-3d27d356f072">

Here you have the chunk of code : 

`        <ng-template pTemplate>
                <ngs-code-editor
                        class="h-full"
                        style='{ "width": "100% !important" }'
                        [theme]="editorTheme"
                        [codeModel]="model"
                        [options]="options"
                        (valueChanged)="onCodeChanged($event)"
                />
        </ng-template>
 `
 
 I localized the problem, it is provoked by the primeng's component p-spiltter, this is a resizable box component.
 Do you have a solution to fix width with the p splitter ? 
 
 I localized the problem, it is provoked by the primeng component p-splitter, this is a resizable box component. Do you have a solution to fix width with the p splitter ?
 
 [Prime Ng splitter component](https://primeng.org/splitter)

**Comment by DenysVuika** [comment]
this component has no relation to PrimeNg
