### ISSUE TITLE
Request: support multiple editors on a single page

### ISSUE THREAD

**Issue by gregpurnell** [ngstack/code-editor#366]
It would be great to support multiple editors on a single page for working with different files simultaneously.

**Currently:**
Currently, when adding two instances of `ngs-code-editor` to the page, only one successfully loads a `monaco-editor`.

**Ideal**
I would love to be able to add multiple `ngs-code-editor` component instances to the page.

**Comment by jonny1811** [comment]
You can use multiple editors on the same page is just pass different parameters.

**Comment by gineign** [comment]
facing the same problem

**Comment by mrbu-solutions** [comment]
Tried passing different model and still not working.
Tried wrapping on template and give different id and doesn't worked too.
Tried wrapping it on a MyEditorComponent and take the type as input, doesn't work as well.
Tried lazy load on a service, doesn't work as well. 

Had you made this singleton?

**Comment by DenysVuika** [comment]
I am working on a fix.

**Comment by DenysVuika** [comment]
Fixed in 2.1.0

**Comment by gineign** [comment]
Can this support angular 9 as well? I can't make 2.1.0 working on my environment

**Comment by DenysVuika** [comment]
What is the issue you have? The repo has a separate project to demo multiple editors, you need just running `npm install && npm serve multiple-editors --open`

**Comment by LiamKenneth** [comment]
I have the same issue with Angular 9
```
  <ngs-code-editor [theme]="theme" [codeModel]="onEnterModel" [options]="options"
                                            (valueChanged)="onCodeChanged($event)">

<ngs-code-editor [theme]="theme" [codeModel]="onLeaveModel" [options]="options"
                                            (valueChanged)="onLeaveChanged($event)"></ngs-code-editor>
```
Using a separate model but still, get this error:
**Error: ModelService: Cannot add model because it already exists!**

**Comment by LiamKenneth** [comment]
I solved it, the issue was the URI was the same value in the 2nd CodeModel, so the error was confusing because it is the same model but assigned to a different property. :) 

```
    onEnterModel: CodeModel = {
        language: 'lua',
        uri: 'lua.json',
        value: '',
    };
    onLeaveModel: CodeModel = {
        language: 'lua',
        uri: 'lua2.json', // was lua.json
        value: '',
    };
```

**Comment by gineign** [comment]
@DenysVuika Thanks for the response and sorry for the late response.

monaco is not defined
![image](https://user-images.githubusercontent.com/7449955/97084190-5093f280-1650-11eb-8cb8-e29c330890ff.png)

I'm using angular 9 on ivy false. is it the reason?

**Comment by DenysVuika** [comment]
@gineign you can use 1.x releases for Angular 9, the 2.x releases are Angular 10

**Comment by gineign** [comment]
Thanks for a quick response
1.x doesn't have multiple editor supports right?

**Comment by DenysVuika** [comment]
Check comments above, maybe https://github.com/ngstack/code-editor/issues/366#issuecomment-699594058 works for you with Angular 9. But there were fixes for 2.x branch, yes.

**Comment by DenysVuika** [comment]
@gineign having `monaco is not defined` too, investigating right now
