### ISSUE TITLE
Updating value later on

### ISSUE THREAD

**Issue by fitness23** [ngstack/code-editor#476]
The current system is fine if we know what the initial value is.
However when we get data from an api and wish to update the model's value this doesn't work.

I tried `this.codeModel.value = "alert('This is the new code from the api');";`

But this doesn't work, the editor still shows the original value. Please could this feature be added?

**Comment by fitness23** [comment]
Ah I got it. For anyone stumped with this problem, you need to declare the entire object again. For example after your api has loaded:

```
this.codeModel = {
                            language: 'javascript',
                            value: this.myForm.controls.code['controls'].create.value,
                          };
```

**Comment by DenysVuika** [comment]
Ok, closing as you have found the solution.
