### ISSUE TITLE
How do I get an instance of the editor in Angular because I want to format the code in the editor

### ISSUE THREAD

**Issue by SuperRichZhao** [ngstack/code-editor#484]
Hello, I introduced \@ngstack/code-editor, and it ran successfully, but I put the assembled code into the editor, the format looks not so beautiful, how to get the instance of the editor, do I want to format the code, or is there any other solution? Thank you

**Comment by DenysVuika** [comment]
With 7.2.0, you can access the editor component and underlying monaco instance. See https://github.com/ngstack/code-editor/tree/v.7.2.0?tab=readme-ov-file#accessing-code-editor-instance for more details
