### ISSUE TITLE
'ngs-code-editor' is not a known element

### ISSUE THREAD

**Issue by sehati** [ngstack/code-editor#491]
using in a lazy loaded module work fine but there is this error
'ngs-code-editor' is not a known element:
1. If 'ngs-code-editor' is an Angular component, then verify that it is part of this module.
2. If 'ngs-code-editor' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ng

**Comment by DenysVuika** [comment]
Please check the Lazy Loading section in the main README file
