### ISSUE TITLE
Code editor won't render until page resize

### ISSUE THREAD

**Issue by DominoPivot** [ngstack/code-editor#510]
__Angular version: 9
code-editor version: 2.1.1__

In my application, I'm using a `<mat-tab>` that contains a custom component which itself contains the `<ngs-code-editor>`. For a reason I can't pinpoint, the code editor won't render until the page is resized by the user. To be exact, only a dark rectangle shows. This is the code for my custom component:

```html
<ngs-code-editor
  [theme]="theme"
  [codeModel]="codeModel"
  [options]="options"
  (valueChanged)="onCodeChanged($event)">
</ngs-code-editor>
```

```ts
export class MyEditorComponent implements OnInit {
  @Input('form') mainForm: FormGroup;

  theme = 'vs-dark';
  options = {
    contextmenu: true,
    lineNumbers: true,
    minimap: {
      enabled: true,
    },
  };
  codeModel: CodeModel = {
    language: 'json',
    uri: 'main.json',
    value: '{}',
  };

  ngOnInit(): void {
    this.codeModel.value = this.mainForm.get('data').value;
  }

  onCodeChanged(evt: string): void {
    this.mainForm.get('data').setValue(evt);
  }
}
```

As a workaround, I've added an `*ngIf="showEditor"` on the editor, which I set to true in a `setTimeout(..., 0)` call from the `ngOnInit`. This somehow works. This could very well be a me problem more than a problem with this component, I'm fairly new to angular.

**Comment by tom-englert** [comment]
@DominoPivot maybe because you are mutating codeModel:
```ts
ngOnInit(): void {
    this.codeModel.value = this.mainForm.get('data').value;
}
```
to trigger a change detection you may need to treat `this.codeModel` as immutable, and not change it's value property:
```ts
this.codeModel = { ...this.codeModel, value: this.mainForm.get('data').value };
```

**Comment by DominoPivot** [comment]
Back when I opened this issue I had a very poor understanding of Angular's change detection mechanics, partly because the code base I was trying to learn from was full of mutations like this.

I have since quit that job and therefore no longer have access to the code to test it, so I'll close this issue.
