### ISSUE TITLE
Ivy Renderer issues on re-compile

### ISSUE THREAD

**Issue by markmakes** [ngstack/code-editor#52]
I know the simple fix is to disable the new Ivy Renderer, but since Angular is moving forward with Ivy soon... 

After a fresh `ng serve`, the code editor displays, but after one re-compile the code editor breaks.

`ERROR Error: Template error: Can't bind to 'theme' since it isn't a known property of 'ngs-code-editor'.`

**Comment by DenysVuika** [comment]
Thanks, I will try to make the code compatible with Ivy.

**Comment by DenysVuika** [comment]
I am waiting for Angular 9 as at this point nothing is compatible with Ivy, given the status of Ivy in Angular 8 and the fact it is disabled by default.

**Comment by markmakes** [comment]
@DenysVuika sounds good! thanks!
