### ISSUE TITLE
Cannot read property 'monaco' of null

### ISSUE THREAD

**Issue by tjhainer** [ngstack/code-editor#590]
Console errors

![image](https://user-images.githubusercontent.com/28038537/114270941-6d956580-99e5-11eb-9a45-28b9a5d88f20.png)

Likely because https://github.com/ngstack/code-editor/blob/master/projects/code-editor/src/lib/services/code-editor.service.ts#L33 

the loaded BehaviourSubject is initially set to null. In the Default services the BehaviourSubject is subscribed to, and event.monaco is accessed but event is initially null.

![image](https://user-images.githubusercontent.com/28038537/114271016-bf3df000-99e5-11eb-9da0-aec53b61e985.png)

Modifying the source in node_modules, setting initial value to {} does not give these console errors. Also changing it to Subject instead of BehaviourSubject works as well.

**Comment by DenysVuika** [comment]
Fixed, thanks
