### ISSUE TITLE
Lazy load of editor in module

### ISSUE THREAD

**Issue by SitecHQ** [ngstack/code-editor#628]
When I add  CodeEditorModule.forRoot() in my app.module.ts and  CodeEditorModule.forChild() in my lazyload.module.ts, the editor is loaded after startup even if the lazy load module is not. 

Editor files from content delivery network should loaded only if lazy loaded modul loaded

**Comment by CharlieGreenman** [comment]
If you end up following the instructions for allowing offline access, it will partially sidestep this problem. Takes me 45ms to load ngstack/code-editor locally.

**Comment by CharlieGreenman** [comment]
For what it's worth, I ended up moving off this library and creating my own homegrown version. I found it ended up messing with the performance of the application too much

**Comment by mfp22** [comment]
Nice. If you end up publishing it, I might use it. For now I consider my solution technical debt

**Comment by CharlieGreenman** [comment]
We will think about it. In the meantime, I sent you an email if interested
