### ISSUE TITLE
How can I modify the editor height?

### ISSUE THREAD

**Issue by javgat** [ngstack/code-editor#658]
I would love to increase the height of the editor, as it only shows like 10 lines at the same time, but I don't know how.

**Comment by DenysVuika** [comment]
maybe something wrong with your application or styles... you can check the example applications coming with this repo and editors take full height

**Comment by javgat** [comment]
Yes, my bad, sorry.

I was editing the height value of the "ngs-code-editor" tag, instead of its parent's. Now it works great. Thanks for creating this component btw :+1: .
