### ISSUE TITLE
Can't Adjust height

### ISSUE THREAD

**Issue by Sagato** [ngstack/code-editor#918]
I am not able to adjust the height of the editor by any means.

**Comment by mirupal** [comment]
Looking at the code height is inherited (I'm on version 1.0.0).

I needed to set the height to 100% on the surrounding element _and_ on the component itself.

This worked for me
```html
<div style="height: 100%">
  <ngs-code-editor style="height: 100%"></ngs-code-editor>
</div>
```

**Comment by DenysVuika** [comment]
there's a working demo application with full height, you can clone the repo and run "npm start" and see the code
