### ISSUE TITLE
How to add multiple editors inside *ngfor in angular

### ISSUE THREAD

**Issue by XI-3337-Madhan-J** [ngstack/code-editor#936]
Hi team,
Need to implement the  code editor inside dynamic tabs any help would be appreciated

**Comment by DenysVuika** [comment]
To see how to run multiple editors on the same page you can check the `multiple-editors` example:

```
ng serve multiple-editors
```

regarding tabs, it's up to you how to implement this, not sure it's the issue related to this repo
