### ISSUE TITLE
Code window is blank until window resizes

### ISSUE THREAD

**Issue by NewToStuff** [ngstack/code-editor#995]
Hi,

I am experiencing an issue similar to this:
https://github.com/ngstack/code-editor/issues/510

Basically the code window appears blank until the page resizes I believe by running the window:resize event. 

```
  @HostListener('window:resize')
  onResize() {
    if (this._editor) {
      this._editor.layout();
    }
  }

```

The Angular Material Sidenav (https://material.angular.io/components/sidenav/overview) is closed when the editor component is created. The sideNav opens at some time later.

I think the onResize() function basically needs to be called when the sideNav opens  If I remember correctly the width will start as 0 when created within a SideNav (or in the Mat-Tab example the other poster had)

Is there something to do to make this compatible and/or call onResize().

EDIT: After further investigation the issue seems to be triggered by putting the code to call the editor inside an <amplify-authenticator> which wraps the entire application and cannot be removed. 

``` html

<amplify-authenticator>
       <ngs-code-editor
        [theme]="theme"
        [codeModel]="codeModel"
        [options]="options"
        (valueChanged)="onCodeChanged($event)"
      >
      </ngs-code-editor>
</amplify-authenticator>
```

Thanks

**Comment by FalzoNe007** [comment]
I have found for me to be working when i put 
`automaticLayout: true`
in 'options' initialization for the editor.
